import{a as f,S as y,i as n}from"./assets/vendor-BDaiwwc1.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const p="49021179-e432bb9a2ad6e70ca9f1cd413",L="https://pixabay.com/api/";async function m(r,e=20){try{return(await f.get(L,{params:{key:p,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:40}})).data.hits}catch(i){return console.error("Error fetching images:",i),[]}}function g(r){const e=r.map(o=>`<a href="${o.largeImageURL}" class="gallery-item">
                <img src="${o.webformatURL}" alt="${o.tags}">
                <div class="info">
                    <p><b>Likes:</b> ${o.likes}</p>
                    <p><b>Views:</b> ${o.views}</p>
                    <p><b>Comments:</b> ${o.comments}</p>
                    <p><b>Downloads:</b> ${o.downloads}</p>
                </div>
            </a>`).join("");gallery.innerHTML=e,new y(".gallery a").refresh()}const b=document.querySelector(".search-form"),w=document.querySelector(".gallery"),a=document.querySelector(".loader"),c=document.querySelector(".load-more-button"),h=document.querySelector(".end-message");let l="",d=1;b.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements[0].value.trim(),!l){n.warning({message:"Please enter a search query!"});return}w.innerHTML="",a.classList.remove("hidden"),c.classList.add("hidden"),h.classList.add("hidden");try{const e=await m(l,d);if(a.classList.add("hidden"),e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(e.hits),e.totalHits>40&&c.classList.remove("hidden"),e.totalHits<=d*40&&(c.classList.add("hidden"),h.classList.remove("hidden"))}catch{a.classList.add("hidden"),n.error({message:"Something went wrong. Please try again."})}});c.addEventListener("click",async()=>{d+=1,a.classList.remove("hidden");try{const r=await m(l,d);if(a.classList.add("hidden"),r.hits.length===0){n.error({message:"Sorry, there are no more images matching your search query."});return}g(r.hits);const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"}),r.totalHits<=d*40&&(c.classList.add("hidden"),h.classList.remove("hidden"))}catch{a.classList.add("hidden"),n.error({message:"Something went wrong. Please try again."})}});
//# sourceMappingURL=index.js.map
